
// Images.cs

/*
 * This class contains global Bitmap variables containing images loaded from
 * resource streams compiled into the executable. All of these images where
 * generated by the Graphics.exe companion program, although the product icons
 * are based on photographic images.
 * 
 */

using System;
using System.Drawing;
using System.Reflection;
using System.IO;
using System.Globalization;

namespace Rails
{
	public sealed class Images
	{
		public static Bitmap BlackDot;			// a clear milepost
		public static Bitmap BlueDot;			// a sea-lane milepost
		public static Bitmap Hill;				// a mountain milepost (black triangle)
		public static Bitmap Alpine;			// an alpine milepost (hollow black triangle)

		public static Bitmap Capital;			// a major city (red hexagon)
		public static Bitmap City;				// a minor city (red square)
		public static Bitmap Town;				// a town (red circle)

		public static Bitmap Port;				// a port (grey circle with "P")

		public static Bitmap Glow;				// blue glow around highlighted city

		public static Icon HumanIcon;			// user.ico
		public static Icon ComputerIcon;		// computer.ico

		public static Bitmap LocoBitmap;		// train gif by Chris Denbow

		public static Bitmap[] TrainDot;		// colored center of train indicators
		public static Bitmap[] TrainPointer;	// directional train indicators

		public static Bitmap[,] TrackBitmap;	// player-color tracks in three orientations
		public static Bitmap[,] BridgeBitmap;	// player-colored tracks over rivers

		public static Bitmap[] Snowflake;		// a variety of snowflakes for snow events

		static Assembly assembly;

		private Images()
		{
		}

		static Images()
		{
			assembly = Assembly.GetExecutingAssembly();

			BlackDot = GetBitmap("BlackDot");
			BlueDot = GetBitmap("BlueDot");
			Hill = GetBitmap("Hill");
			Alpine = GetBitmap("Alpine");
			Capital = GetBitmap("Capital");
			City = GetBitmap("City");
			Town = GetBitmap("Town");
			Port = GetBitmap("Port");
			Glow = GetBitmap("Glow");
			HumanIcon = GetIcon("user");
			ComputerIcon = GetIcon("machine");
			LocoBitmap = (Bitmap) GetImage("Rails.Trains.Loco.gif");
			TrainDot = new Bitmap[6];
			TrainPointer = new Bitmap[6];
			NumberFormatInfo format = CultureInfo.InvariantCulture.NumberFormat;
			for (int i=0; i<6; i++)
			{
				TrainDot[i] = GetBitmap("PlayerDot" + i.ToString(format));
				TrainPointer[i] = GetBitmap("Train" + i.ToString(format));
			}
			TrackBitmap = new Bitmap[7,3];
			BridgeBitmap = new Bitmap[7,3];
			for (int i=0; i<7; i++)
				for (int j=0; j<3; j++)
				{
					TrackBitmap[i, j] = GetBitmap("Track" + i.ToString(format) + "-" + j.ToString(format));
					BridgeBitmap[i, j] = GetBitmap("Bridge" + i.ToString(format) + "-" + j.ToString(format));
				}
			Snowflake = new Bitmap[10];
			for (int i=0; i<10; i++)
				Snowflake[i] = GetBitmap("Snowflake" + i.ToString(format));
		}

		static Bitmap GetBitmap(string name)
		{
			string resourceName = String.Format(System.Globalization.CultureInfo.InvariantCulture, "Rails.Graphics.bin.Debug.{0}.bmp", name);
			return (Bitmap) GetImage(resourceName);
		}

		static Image GetImage(string resourceName)
		{
			Stream stream = assembly.GetManifestResourceStream(resourceName);
			Image image = Image.FromStream(stream);
			stream.Close();
			return image;
		}

		static Icon GetIcon(string name)
		{
			string resourceName = String.Format(System.Globalization.CultureInfo.InvariantCulture, "Rails.{0}.ico", name);
			Stream stream = assembly.GetManifestResourceStream(resourceName);
			Icon icon = new Icon(stream);
			stream.Close();
			return icon;
		}

	}
}
